package com.grupo11.magenta.vistas;

import com.grupo11.magenta.modelos.Cartelera;
import com.grupo11.magenta.modelos.Pelicula;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

public class BuscarPeliculaPanel extends JPanel {

    private final Cartelera cartelera = new Cartelera();
    private JTextField busquedaField = new JTextField(20);
    private JButton buscarButton = new JButton("Buscar");
    private JTable tablaResultados;
    private DefaultTableModel tablaModelo;

    public BuscarPeliculaPanel() {
        setLayout(new BorderLayout());

        JPanel panelSuperior = new JPanel();
        panelSuperior.add(new JLabel("Título:"));
        panelSuperior.add(busquedaField);
        panelSuperior.add(buscarButton);
        add(panelSuperior, BorderLayout.NORTH);

        String[] columnas = {"ID", "Título", "Director", "Año", "Duración", "Género"};
        tablaModelo = new DefaultTableModel(columnas, 0);
        tablaResultados = new JTable(tablaModelo);
        JScrollPane scrollPane = new JScrollPane(tablaResultados);
        add(scrollPane, BorderLayout.CENTER);

        buscarButton.addActionListener(e -> buscarPeliculas());
    }

    private void buscarPeliculas() {
        tablaModelo.setRowCount(0);
        String tituloBusqueda = busquedaField.getText();
        
        List<Pelicula> peliculas = cartelera.buscarPeliculasPorTitulo(tituloBusqueda);
        
        for (Pelicula p : peliculas) {
            Object[] fila = {
                p.getId(),
                p.getTitulo(),
                p.getDirector(),
                p.getAnio(),
                p.getDuracion(),
                p.getGenero()
            };
            tablaModelo.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
