package com.grupo11.magenta.vistas;

import com.grupo11.magenta.interfaces.RefreshListener;
import com.grupo11.magenta.modelos.Cartelera;
import com.grupo11.magenta.modelos.Pelicula;

import javax.swing.*;
import java.awt.*;

public class ActualizarPeliculaPanel extends JPanel {

    private final Cartelera cartelera = new Cartelera();
    private final RefreshListener listener;

    private JTextField idField = new JTextField(5);
    private JTextField tituloField = new JTextField(20);
    private JTextField directorField = new JTextField(20);
    private JTextField anioField = new JTextField(10);
    private JTextField duracionField = new JTextField(10);
    private JComboBox<String> generoComboBox; // Cambiado a JComboBox
    private JButton actualizarButton = new JButton("Actualizar Película");

    public ActualizarPeliculaPanel(RefreshListener listener) {
        this.listener = listener;

        // Inicializar el JComboBox con los géneros
        String[] generos = {"Comedia", "Drama", "Accion", "Ciencia ficcion", "Terror", "Animacion", "Aventura", "Musical"};
        generoComboBox = new JComboBox<>(generos);
        
        setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5);
        gbc.anchor = GridBagConstraints.WEST;

        gbc.gridx = 0; gbc.gridy = 0;
        add(new JLabel("ID de la película:"), gbc);
        gbc.gridx = 1;
        add(idField, gbc);

        gbc.gridx = 0; gbc.gridy = 1;
        add(new JLabel("Nuevo Título:"), gbc);
        gbc.gridx = 1;
        add(tituloField, gbc);

        gbc.gridx = 0; gbc.gridy = 2;
        add(new JLabel("Nuevo Director:"), gbc);
        gbc.gridx = 1;
        add(directorField, gbc);

        gbc.gridx = 0; gbc.gridy = 3;
        add(new JLabel("Nuevo Año:"), gbc);
        gbc.gridx = 1;
        add(anioField, gbc);

        gbc.gridx = 0; gbc.gridy = 4;
        add(new JLabel("Nueva Duración (min):"), gbc);
        gbc.gridx = 1;
        add(duracionField, gbc);
        
        gbc.gridx = 0; gbc.gridy = 5;
        add(new JLabel("Nuevo Género:"), gbc);
        gbc.gridx = 1;
        add(generoComboBox, gbc);

        gbc.gridx = 0; gbc.gridy = 6;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.CENTER;
        add(actualizarButton, gbc);

        actualizarButton.addActionListener(e -> actualizarPelicula());
    }

    private void actualizarPelicula() {
        try {
            int id = Integer.parseInt(idField.getText());
            String titulo = tituloField.getText();
            String director = directorField.getText();
            int anio = Integer.parseInt(anioField.getText());
            int duracion = Integer.parseInt(duracionField.getText());
            String genero = (String) generoComboBox.getSelectedItem();

            Pelicula peliculaActualizada = new Pelicula(id, titulo, director, anio, duracion, genero);
            cartelera.actualizarPelicula(peliculaActualizada);
            
            JOptionPane.showMessageDialog(this, "Película actualizada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
            if (listener != null) {
                listener.onRefreshNeeded(); // Notificamos al listener para que actualice la tabla
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El ID, año y duración deben ser números válidos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
